use std::fs;
use std::io::{BufReader, Read, Seek, SeekFrom, Write};
use std::path::Path;
use sha2::{Digest, Sha256, Sha512};
use tauri::{AppHandle, Manager};

// ── Checksum generation ───────────────────────────────────────────────────────

/// Generate a checksum sidecar file for the given file paths.
/// `algorithm`: "md5" | "sha256" | "sha512"
/// `output_path`: full path where the .md5 / .sha256 file will be written.
#[tauri::command]
pub fn generate_checksums(
    paths: Vec<String>,
    algorithm: String,
    output_path: String,
) -> Result<(), String> {
    let algo = algorithm.to_lowercase();
    let mut lines = Vec::with_capacity(paths.len());

    for path_str in &paths {
        let path = Path::new(path_str);
        if !path.is_file() {
            continue;
        }
        let hash = match algo.as_str() {
            "md5"    => hash_md5(path)?,
            "sha256" => hash_sha256(path)?,
            "sha512" => hash_sha512(path)?,
            other    => return Err(format!("Unsupported algorithm: {}", other)),
        };
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or(path_str);
        lines.push(format!("{}  {}", hash, name));
    }

    let content = format!("# {} checksums generated by NexExplorer\n{}\n",
        algo.to_uppercase(), lines.join("\n"));

    fs::write(&output_path, content)
        .map_err(|e| format!("Failed to write checksum file: {}", e))?;
    Ok(())
}

fn hash_md5(path: &Path) -> Result<String, String> {
    let data = fs::read(path).map_err(|e| e.to_string())?;
    let digest = md5::compute(&data);
    Ok(format!("{:x}", digest))
}

fn hash_sha256(path: &Path) -> Result<String, String> {
    let file = fs::File::open(path).map_err(|e| e.to_string())?;
    let mut reader = BufReader::with_capacity(256 * 1024, file);
    let mut hasher = Sha256::new();
    let mut buf = vec![0u8; 256 * 1024];
    loop {
        let n = reader.read(&mut buf).map_err(|e| e.to_string())?;
        if n == 0 { break; }
        hasher.update(&buf[..n]);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

fn hash_sha512(path: &Path) -> Result<String, String> {
    let file = fs::File::open(path).map_err(|e| e.to_string())?;
    let mut reader = BufReader::with_capacity(256 * 1024, file);
    let mut hasher = Sha512::new();
    let mut buf = vec![0u8; 256 * 1024];
    loop {
        let n = reader.read(&mut buf).map_err(|e| e.to_string())?;
        if n == 0 { break; }
        hasher.update(&buf[..n]);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

// ── Secure delete ─────────────────────────────────────────────────────────────

/// Overwrite each file with `passes` rounds of patterns, then delete.
/// passes: 1 (zeros), 3 (DoD basic), 7 (DoD full)
#[tauri::command]
pub fn secure_delete_files(paths: Vec<String>, passes: u32) -> Result<(), String> {
    let passes = passes.clamp(1, 7);
    for path_str in &paths {
        let path = Path::new(path_str);
        if path.is_dir() {
            secure_wipe_dir(path, passes)?;
        } else if path.is_file() {
            secure_wipe_file(path, passes)?;
        }
    }
    Ok(())
}

fn secure_wipe_file(path: &Path, passes: u32) -> Result<(), String> {
    let len = path.metadata()
        .map_err(|e| format!("stat {}: {}", path.display(), e))?.len();

    if len > 0 {
        let mut file = fs::OpenOptions::new().write(true).open(path)
            .map_err(|e| format!("open {} for wipe: {}", path.display(), e))?;

        let chunk = (256 * 1024).min(len as usize);
        for pass in 0..passes {
            let pattern: u8 = match pass % 3 {
                0 => 0x00,
                1 => 0xFF,
                _ => 0x92u8.wrapping_add(pass as u8), // pseudo-random byte
            };
            let buf = vec![pattern; chunk];
            file.seek(SeekFrom::Start(0)).map_err(|e| e.to_string())?;
            let mut written = 0u64;
            while written < len {
                let n = ((len - written) as usize).min(chunk);
                file.write_all(&buf[..n]).map_err(|e| e.to_string())?;
                written += n as u64;
            }
            file.sync_all().map_err(|e| e.to_string())?;
        }
    }

    fs::remove_file(path)
        .map_err(|e| format!("delete {} after wipe: {}", path.display(), e))?;
    Ok(())
}

fn secure_wipe_dir(path: &Path, passes: u32) -> Result<(), String> {
    for entry in walkdir::WalkDir::new(path).contents_first(true).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() {
            secure_wipe_file(entry.path(), passes)?;
        } else if entry.file_type().is_dir() {
            fs::remove_dir(entry.path())
                .map_err(|e| format!("remove dir {}: {}", entry.path().display(), e))?;
        }
    }
    Ok(())
}

// ── Run completion script ─────────────────────────────────────────────────────

/// Launch a batch/powershell script detached after a transfer completes.
#[tauri::command]
pub fn run_completion_script(script_path: String) -> Result<(), String> {
    let trimmed = script_path.trim();
    if trimmed.is_empty() { return Ok(()); }
    let path = Path::new(trimmed);
    if !path.exists() {
        return Err(format!("Script not found: {}", trimmed));
    }

    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("").to_lowercase();
        let mut cmd = if ext == "ps1" {
            let mut c = std::process::Command::new("powershell.exe");
            c.args(["-ExecutionPolicy", "Bypass", "-File", trimmed]);
            c
        } else {
            let mut c = std::process::Command::new("cmd.exe");
            c.args(["/c", trimmed]);
            c
        };
        cmd.creation_flags(CREATE_NO_WINDOW).spawn()
            .map_err(|e| format!("Failed to launch script: {}", e))?;
    }
    #[cfg(not(target_os = "windows"))]
    {
        std::process::Command::new("sh").arg(trimmed).spawn()
            .map_err(|e| format!("Failed to launch script: {}", e))?;
    }
    Ok(())
}

// ── Export transfer log ───────────────────────────────────────────────────────

/// Read the daily JSON transfer log and export as HTML or CSV.
/// `date`: "YYYY-MM-DD" (empty = today)
/// `format`: "html" | "csv"
/// `output_path`: destination file path
#[tauri::command]
pub fn export_transfer_log(
    app: AppHandle,
    date: String,
    format: String,
    output_path: String,
) -> Result<(), String> {
    let app_data = app.path().app_data_dir()
        .map_err(|e| format!("Cannot get app data dir: {}", e))?;

    let day = if date.trim().is_empty() {
        chrono::Local::now().format("%Y-%m-%d").to_string()
    } else {
        date.trim().to_string()
    };

    let log_path = app_data.join("transfer_logs").join(format!("{}.json", day));
    let json_str = fs::read_to_string(&log_path)
        .map_err(|_| format!("No transfer log found for {}", day))?;

    let entries: Vec<serde_json::Value> = serde_json::from_str(&json_str)
        .map_err(|e| format!("Failed to parse log: {}", e))?;

    let content = match format.to_lowercase().as_str() {
        "csv"  => build_csv(&entries),
        "html" => build_html(&entries, &day),
        other  => return Err(format!("Unknown format: {}", other)),
    };

    fs::write(&output_path, content)
        .map_err(|e| format!("Failed to write export: {}", e))?;
    Ok(())
}

fn build_csv(entries: &[serde_json::Value]) -> String {
    let mut out = String::from("id,op,status,files_done,files_total,bytes_done,bytes_total,duration_seconds,started_at,finished_at,failed_files\n");
    for e in entries {
        let failed = e["failed_files"].as_array()
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join("; "))
            .unwrap_or_default();
        out.push_str(&format!(
            "{},{},{},{},{},{},{},{},{},{},\"{}\"\n",
            e["id"].as_str().unwrap_or(""),
            e["op"].as_str().unwrap_or(""),
            e["status"].as_str().unwrap_or(""),
            e["files_done"].as_u64().unwrap_or(0),
            e["files_total"].as_u64().unwrap_or(0),
            e["bytes_done"].as_u64().unwrap_or(0),
            e["bytes_total"].as_u64().unwrap_or(0),
            e["duration_seconds"].as_u64().unwrap_or(0),
            e["started_at"].as_str().unwrap_or(""),
            e["finished_at"].as_str().unwrap_or(""),
            failed.replace('"', "\"\""),
        ));
    }
    out
}

fn build_html(entries: &[serde_json::Value], day: &str) -> String {
    let rows: String = entries.iter().map(|e| {
        let status = e["status"].as_str().unwrap_or("");
        let status_color = match status {
            "Completed" => "#4ade80",
            "Failed"    => "#f87171",
            _           => "#94a3b8",
        };
        let failed_count = e["failed_files"].as_array().map(|a| a.len()).unwrap_or(0);
        format!(
            "<tr><td>{}</td><td>{}</td><td style='color:{}'>{}</td><td>{}/{}</td><td>{}</td><td>{}s</td><td>{}</td></tr>",
            e["id"].as_str().unwrap_or(""),
            e["op"].as_str().unwrap_or(""),
            status_color, status,
            e["files_done"].as_u64().unwrap_or(0),
            e["files_total"].as_u64().unwrap_or(0),
            fmt_bytes(e["bytes_total"].as_u64().unwrap_or(0)),
            e["duration_seconds"].as_u64().unwrap_or(0),
            if failed_count > 0 { format!("<span style='color:#f87171'>{} failed</span>", failed_count) } else { "—".into() },
        )
    }).collect();

    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NexExplorer Transfer Log — {day}</title>
<style>
  body {{ font-family: system-ui, sans-serif; background: #0f0f0f; color: #e2e8f0; margin: 0; padding: 24px; }}
  h1   {{ font-size: 18px; font-weight: 600; margin-bottom: 16px; color: #fff; }}
  table{{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th   {{ text-align: left; padding: 8px 12px; background: #1e1e1e; color: #94a3b8; font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.4px; border-bottom: 1px solid #2d2d2d; }}
  td   {{ padding: 8px 12px; border-bottom: 1px solid #1e1e1e; vertical-align: top; }}
  tr:hover td {{ background: #1a1a1a; }}
</style>
</head>
<body>
<h1>Transfer Log — {day}</h1>
<table>
<thead><tr><th>ID</th><th>Op</th><th>Status</th><th>Files</th><th>Size</th><th>Duration</th><th>Failures</th></tr></thead>
<tbody>{rows}</tbody>
</table>
</body>
</html>"#)
}

fn fmt_bytes(b: u64) -> String {
    if b == 0 { return "0 B".into(); }
    let units = ["B", "KB", "MB", "GB", "TB"];
    let i = (b as f64).log(1024.0).floor() as usize;
    let i = i.min(units.len() - 1);
    format!("{:.1} {}", b as f64 / 1024f64.powi(i as i32), units[i])
}
